### ISSUE TITLE
Are all files under dist folder necessary?

### ISSUE THREAD

**Issue by nolsherry** [720kb/radiobox.css#6]
Hello @45kb ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
There are some problems which need to confirm with you. 
Are all files under `dist` folder necessary?(such as `scss` folder, some files under `css` folder excluded `dist/css/radiobox.min.css`)
Or just only need `dist/css/radiobox.min.css` file?
thanks!

cdnjs/cdnjs#8969

**Comment by 45kb** [comment]
Hi @nolsherry thanks for asking this.
The only file needed is `dist/css/radiobox.min.css`, you can skip any other file. 
Then if you can and you do include also all the other files inside `dist/css`.... we'll be much grateful!

Just let know if any other doubt 👍

**Comment by nolsherry** [comment]
@45kb , thanks for your response.
